### ISSUE TITLE
Request for prebuilt patched kernels for RPM based distros

### ISSUE THREAD

**Issue by daeSundae** [amonet-kamakiri/prebuilt-kernels#1]
Hi. Thanks for the prebuilt kernels, they help quite alot. I'm currently using Fedora and there aren't any prebuilt kernels for RPM based distros and the kernel patch is for 4.14 kernel so I would have to downgrade too. Is it possible if you could make prebuilt patch-applied kernels for RPM based distros too?

**Comment by chaosmaster** [comment]
Unfortunately I don't use Fedora.
You might check out the [Fedora Wiki](https://fedoraproject.org/wiki/Building_a_custom_kernel) how to compile a custom kernel.

Attached an updated kernel-patch that works with 5.10

[disable-usb-checks-5.10.patch.txt](https://github.com/amonet-kamakiri/prebuilt-kernels/files/6132001/disable-usb-checks-5.10.patch.txt)

**Comment by daeSundae** [comment]
> Unfortunately I don't use Fedora.
> You might check out the [Fedora Wiki](https://fedoraproject.org/wiki/Building_a_custom_kernel) how to compile a custom kernel.
> 
> Attached an updated kernel-patch that works with 5.10
> 
> [disable-usb-checks-5.10.patch.txt](https://github.com/amonet-kamakiri/prebuilt-kernels/files/6132001/disable-usb-checks-5.10.patch.txt)

Hi. Thanks for the updated kernel-patch. I'll patch myself.
